cc_binary(
  name = "empty",
  srcs = ["empty.cpp"],
  deps = [
    "@com_google_zetasql//zetasql/public:analyzer",
  ],
)

cc_binary(
  name = "example",
  srcs = ["example.cpp"],
  deps = [
    "@com_google_zetasql//zetasql/public:analyzer",
  ],
)

